global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "voicekart-gateway"
    static_configs:
      - targets: ["gateway_service:8001"]

  - job_name: "voicekart-orchestrator"
    static_configs:
      - targets: ["orchestrator_service:8002"]

  - job_name: "voicekart-tts"
    static_configs:
      - targets: ["tts_service:8003"]

  - job_name: "voicekart-stt"
    static_configs:
      - targets: ["stt_service:8004"]

  - job_name: "voicekart-catalog"
    static_configs:
      - targets: ["catalog_service:8005"]

  - job_name: "voicekart-order"
    static_configs:
      - targets: ["order_service:8006"]
